configure options so gtk1 launcher not built by default, everything else IS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -273,7 +273,7 @@ PACKAGE_BUGREPORT=
 
 ac_unique_file="src/bomns.cpp"
 ac_default_prefix=/usr/local
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS GTK_CONFIG GTK_CFLAGS GTK_LIBS PKG_CONFIG PACKAGE_CFLAGS PACKAGE_LIBS BUILD_LAUNCHER1_TRUE BUILD_LAUNCHER1_FALSE BUILD_LAUNCHER2_TRUE BUILD_LAUNCHER2_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS GTK_CONFIG GTK_CFLAGS GTK_LIBS PKG_CONFIG PACKAGE_CFLAGS PACKAGE_LIBS BUILD_LAUNCHER1_TRUE BUILD_LAUNCHER1_FALSE BUILD_LAUNCHER2_TRUE BUILD_LAUNCHER2_FALSE BUILD_EDITOR_TRUE BUILD_EDITOR_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -824,8 +824,9 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
-  --disable-launcher1     Skip building the GTK+ 1.2.x launcher
+  --enable-launcher1      Build the GTK+ 1.2.x launcher (default = no)
   --disable-launcher2     Skip building the GTK2 launcher
+  --disable-editor        Don't build the (awesome) bomns level editor
   --disable-sdltest       Do not try to compile and run a test SDL program
   --disable-gtktest       Do not try to compile and run a test GTK program
 
@@ -4958,7 +4959,7 @@ if test "${enable_launcher1+set}" = set; then
   enableval="$enable_launcher1"
   build_launcher1="$enableval"
 else
-  build_launcher1="yes"
+  build_launcher1="no"
 fi;
 
 # Check whether --enable-launcher2 or --disable-launcher2 was given.
@@ -4967,6 +4968,14 @@ if test "${enable_launcher2+set}" = set; then
   build_launcher2="$enableval"
 else
   build_launcher2="yes"
+fi;
+
+# Check whether --enable-editor or --disable-editor was given.
+if test "${enable_editor+set}" = set; then
+  enableval="$enable_editor"
+  build_editor="$enableval"
+else
+  build_editor="yes"
 fi;
 
 
@@ -5812,6 +5821,16 @@ fi
 
 
 
+if test "x$build_editor" = xyes; then
+  BUILD_EDITOR_TRUE=
+  BUILD_EDITOR_FALSE='#'
+else
+  BUILD_EDITOR_TRUE='#'
+  BUILD_EDITOR_FALSE=
+fi
+
+
+
                                                                                           ac_config_files="$ac_config_files Makefile src/Makefile src/editor/Makefile src/launcher/Makefile src/launcher2/Makefile graphics/Makefile sounds/Makefile m4/Makefile levels/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -5943,6 +5962,13 @@ if test -z "${BUILD_LAUNCHER2_TRUE}" && test -z "${BUILD_LAUNCHER2_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_LAUNCHER2\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"BUILD_LAUNCHER2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${BUILD_EDITOR_TRUE}" && test -z "${BUILD_EDITOR_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"BUILD_EDITOR\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"BUILD_EDITOR\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6557,6 +6583,8 @@ s,@BUILD_LAUNCHER1_TRUE@,$BUILD_LAUNCHER1_TRUE,;t t
 s,@BUILD_LAUNCHER1_FALSE@,$BUILD_LAUNCHER1_FALSE,;t t
 s,@BUILD_LAUNCHER2_TRUE@,$BUILD_LAUNCHER2_TRUE,;t t
 s,@BUILD_LAUNCHER2_FALSE@,$BUILD_LAUNCHER2_FALSE,;t t
+s,@BUILD_EDITOR_TRUE@,$BUILD_EDITOR_TRUE,;t t
+s,@BUILD_EDITOR_FALSE@,$BUILD_EDITOR_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
